name: s15p21e206

services:
  # Frontend 컨테이너 설정

  frontend:
    build:
      context: ./frontend
    image: frontend:dev
    container_name: frontend
    ports:
      - "127.0.0.1:3000:80"


  # MySQL 컨테이너 설정

  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -uroot -p\"$${MYSQL_ROOT_PASSWORD}\" --silent"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend-spring:
    build:
      context: ./backend/spring
    image: backend-spring:dev
    container_name: backend-spring
    ports:
      - "127.0.0.1:8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      DB_URL: "jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul"
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy


  # FastAPI 컨테이너 설정

  backend-fastapi:
    build:
      context: ./backend/fastapi
    image: backend-fastapi:dev
    container_name: backend-fastapi
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      NEO4J_URI: ${NEO4J_URI}
      NEO4J_USERNAME: ${NEO4J_USERNAME}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
    depends_on:
      neo4j:
        condition: service_healthy


  # Neo4j 컨테이너 설정

  neo4j:
    image: neo4j:5.26
    container_name: neo4j
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}
    volumes:
      - neo4j_data:/data
      - ./backend/fastapi/migrations/neo4j:/migrations:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://127.0.0.1:7474 || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

  # Redis 컨테이너 설정
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped

    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--requirepass",
        "${REDIS_PASSWORD}"
      ]

    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

    volumes:
      - redis_data:/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "redis-cli -a \"$$REDIS_PASSWORD\" ping | grep PONG"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mysql_data:
  neo4j_data:
  redis_data: