app.cors.allowed-origins=http://localhost:3000

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

spring.datasource.url=jdbc:h2:mem:starlight_news;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
