app.cors.allowed-origins=http://localhost:3000,http://localhost:5173

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

logging.level.com.starlightnews.backend=DEBUG
