app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

logging.level.com.starlightnews.backend=INFO
